# Generated by Django 5.0 on 2023-12-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EatingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('username', models.CharField(verbose_name='Пользователь')),
                ('breakfast', models.CharField(max_length=100, verbose_name='Завтрак')),
                ('lunch', models.CharField(max_length=100, verbose_name='Обед')),
                ('dinner', models.CharField(max_length=100, verbose_name='Ужин')),
                ('snack', models.CharField(max_length=100, verbose_name='Перекусы')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
                ('birth_date', models.DateField(max_length=50, verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=50, verbose_name='Адрес почты')),
                ('height', models.IntegerField(max_length=50, verbose_name='Рост')),
                ('weight', models.FloatField(max_length=50, verbose_name='Вес')),
            ],
        ),
    ]
